Update github url,  civx path, and build dir

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
 # Parameterize
-PYTHON_VERSION=3.6.4
-BUILDDIR=/tmp/electrum-build
-PACKAGE=Electrum
-GIT_REPO=https://github.com/spesmilo/electrum
+PYTHON_VERSION=3.6.6
+BUILDDIR=/tmp/electrum-civx-build
+PACKAGE=Electrum-CIVX
+GIT_REPO=https://github.com/exofoundation/electrum-civx
 LIBSECP_VERSION=452d8e4d2a2f9f1b5be6b02e18f1ba102e5ca0b4
 
 . $(dirname "$0")/base.sh
@@ -13,7 +13,7 @@ src_dir=$(dirname "$0")
 cd $src_dir/../..
 
 export PYTHONHASHSEED=22
-VERSION=`git describe --tags --dirty`
+VERSION=`git describe --tags`
 
 which brew > /dev/null 2>&1 || fail "Please install brew from https://brew.sh/ to continue"
 
@@ -46,8 +46,8 @@ git submodule update
 rm  -rf $BUILDDIR > /dev/null 2>&1
 mkdir $BUILDDIR
 
-cp -R ./contrib/deterministic-build/electrum-locale/locale/ ./electrum/locale/
-cp    ./contrib/deterministic-build/electrum-icons/icons_rc.py ./electrum/gui/qt/
+cp -R ./contrib/deterministic-build/electrum-civx-locale/locale/ ./electrum/locale/
+cp    ./contrib/deterministic-build/electrum-civx-icons/icons_rc.py ./electrum/gui/qt/
 
 
 info "Downloading libusb..."
@@ -91,4 +91,4 @@ info "Building binary"
 pyinstaller --noconfirm --ascii --clean --name $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"
 
 info "Creating .DMG"
-hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-$VERSION.dmg || fail "Could not create .DMG"
+hdiutil create -fs HFS+ -volname $PACKAGE -srcfolder dist/$PACKAGE.app dist/electrum-civx-$VERSION.dmg || fail "Could not create .DMG"
